name: docker
on:
  push:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' && ( github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'docker:pr-image') )
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - id: docker_meta
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ github.token }}
          tags: |
            type=ref,event=tag
            type=raw,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }},value=${{ github.event.repository.default_branch }}
            type=raw,enable=${{ contains(github.event.pull_request.labels.*.name, 'docker:pr-image') }},value=pr-${{ github.event.pull_request.number }}
          images: |
            ghcr.io/${{ github.repository }}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          build-args: GIT_SHA=${{ github.sha }}
          platforms: linux/amd64,linux/arm64/v8
          pull: true
          push: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || contains(github.event.pull_request.labels.*.name, 'docker:pr-image') }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
